project_id = "fnuabusqvbgvmfeuxrlp"

[functions.auth-login]
verify_jwt = false

[functions.receipts-list]
verify_jwt = false

[functions.receipts-create]
verify_jwt = false

[functions.receipts-update]
verify_jwt = false